trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(581c2850-8085-49b3-87cb-867302365673)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az artifacts universal download \
      --organization "https://dev.azure.com/idr99/" \
      --feed "idr99" \
      --name "iis-sql-stack" \
      --version "0.0.1" \
      --path .
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'